#!/bin/sh
#

if [ ! -e $1.cpp ]; then 
  echo "File $1.cpp doesn't exist !!!"
  exit 1;
fi 

/usr/bin/cpp -I/acc/dsc/tst/data/timing/ctm/OPERLHC/NEXT/mtt $1.cpp $1.ass
../asm.L864 $1.ass $1.obj 
echo "./n" | ../emu.L864 $1.obj

