#!/bin/bash
################################################################################
# @file compiledrvr
#
# @brief Handy driver && installation program compilation script.
#
# @author Yury GEORGIEVSKIY. CERN BE/CO
#
# @date Created on 13/01/2009
################################################################################

# compile for Linux
make clean drvr CPU=L865

# compile for Lynx
make clean drvr CPU=ppc4