#!/bin/bash
################################################################################
# @file compilelib
#
# @brief Script to compile driver library.
#
# @author Yury GEORGIEVSKIY. CERN AB/CO
#
# @date Created on 13/01/2009
#
# @version
################################################################################
