###############################################################################
# @file Makefile.specific
#
# @brief Specific driver description
#
# @author Yury GEORGIEVSKIY
#
# @date Created on 07/04/2009
###############################################################################

CPU  := L865
KVER := 2.6.24.7-rt27