/* ======================================================================================== */
/* Data used to provide Plx9656 field names and addresses of configuration registers        */
/* Julian Lewis 26th Nov 2003. CERN AB/CO/HT Geneva                                         */
/* Julian.Lewis@cern.ch                                                                     */
/* ======================================================================================== */

#include <iofield.h>

#define PlxCONFIG_REGS 40
#define PlxCONFIG_MAX_ADR 0x50

#define PlxLOCAL_REGS 71
#define PlxLOCAL_MAX_ADR 0x104

IoField PlxConfigs[PlxCONFIG_REGS] = {
   { 4, "PCIIDR",    0x00, "PCI Device ID & Vendor ID" },
   { 2, "PCICR",     0x04, "PCI Command" },
   { 2, "PCISR",     0x06, "PCI Status" },
   { 1, "PCIREV",    0x08, "PCI Revision ID" },
   { 1, "PCICCR0",   0x09, "PCI Class code Byte 1" },
   { 1, "PCICCR1",   0x0A, "PCI Class code Byte 2" },
   { 1, "PCICCR2",   0x0B, "PCI Class code Byte 3" },
   { 1, "PCICLSR",   0x0C, "PCI Cash Line Size" },
   { 1, "PCILTR",    0x0D, "PCI Bus Latency Timer" },
   { 1, "PCIHTR",    0x0E, "PCI Header Type" },
   { 1, "PCIBISTR",  0x0F, "PCI PCI Built in Self Test" },
   { 4, "PCIBAR0",   0x10, "PCI BAR0 for Local configuration space mapped" },
   { 4, "PCIBAR1",   0x14, "PCI BAR1 for Local configuration space IO" },
   { 4, "PCIBAR2",   0x18, "PCI BAR2 Local address space 0" },
   { 4, "PCIBAR3",   0x1C, "PCI BAR3 Local address space 1" },
   { 4, "PCIBAR4",   0x20, "PCI BAR4 Local address space 2" },
   { 4, "PCIBAR5",   0x24, "PCI BAR5 Local address space 3" },
   { 4, "PCICIS",    0x28, "PCI Card bus info structure pointer" },
   { 2, "PCISVID",   0x2C, "PCI Subsystem Vendor ID" },
   { 2, "PCISID",    0x2E, "PCI Subsystem ID" },
   { 4, "PCIERBAR",  0x30, "PCI Expansion ROM Base address" },
   { 4, "CAP_PTR",   0x34, "New capability pointer" },
   { 4, "Reserved0", 0x38, "Reserved" },
   { 1, "PCIILR",    0x3C, "PCI Interrupt Line" },
   { 1, "PCIIPR",    0x3D, "PCI Interrupt Pin" },
   { 1, "PCIMGR",    0x3E, "PCI Minimum Grant" },
   { 1, "PCIMLR",    0x3F, "PCI Maximum Latency" },
   { 1, "PMCCAPID",  0x40, "Power Management capability ID" },
   { 1, "PMNEXT",    0x41, "Power Management capability Pointer" },
   { 2, "PMC",       0x42, "Power Management capabilities" },
   { 2, "PMCSR",     0x44, "Power Management Control/Status" },
   { 1, "PMCSR_BSE", 0x46, "PMC Bridge Support Extensisions" },
   { 1, "PMDATA",    0x47, "Power Management Data" },
   { 1, "HS_CNTL",   0x48, "Hot Swap Control" },
   { 1, "HS_NEXT",   0x49, "Hot Swap Next Capability Pointer" },
   { 2, "HS_CSR",    0x4A, "Hot Swap Control Status" },
   { 1, "PVPDCNTL",  0x4C, "PCI Vital Product Data Control" },
   { 1, "PVPD_NEXT", 0x4D, "PCI VPD Next Capability pointer" },
   { 2, "PVPDAD",    0x4E, "PCI VPD Data Address" },
   { 4, "PVPDATA",   0x50, "PCI VPD Data" }
 };

IoField PlxLocals[PlxLOCAL_REGS] = {
   { 4, "LAS0RR",    0x000, "Local Address Space 0 Range" },
   { 4, "LAS0BA",    0x004, "Remap for LAS0RR" },
   { 4, "MARBR",     0x008, "DMA arbitration register" },
   { 1, "BIGEND",    0x00C, "Big/Little endian descriptor" },
   { 1, "LMISC1",    0x00D, "Local miscellaneous control 1" },
   { 1, "PROT_AREA", 0x00E, "Write protect address boundary" },
   { 1, "LMISC2",    0x00F, "Local miscellaneous control 1" },
   { 4, "EROMRR",    0x010, "Direct Slave Expansion ROM range" },
   { 4, "EROMBA",    0x014, "Expansion ROM Local Base Address (Remap)" },
   { 4, "LBRD0",     0x018, "Space 0 Expansion ROM region" },
   { 4, "DMRR",      0x01C, "Local range for Direct Master to PCI" },
   { 4, "DMLBAM",    0x020, "LBA for Direct Master to PCI memory" },
   { 4, "DMLBAI",    0x024, "LBA for Direct Master to PCI I/O config" },
   { 4, "DMPBAM",    0x028, "PBA (Remap) Direct Master to PCI memory" },
   { 4, "DMCFGA",    0x02C, "Config address Direct Master to PCI I/O config" },
   { 4, "OPQIS",     0x030, "Outbound Post Queue Interrupt Status" },
   { 4, "OPQIM",     0x034, "Outbound Post Queue Interrupt Mask" },
   { 4, "Addr38",    0x038, "Reserved" },
   { 4, "Addr3C",    0x03C, "Reserved" },
   { 4, "MBOX0_IQP", 0x040, "Mailbox 0 / Inbound  Queue pointer" },
   { 4, "MBOX1_OQP", 0x044, "Mailbox 1 / Outbound Queue pointer" },
   { 4, "MBOX2",     0x048, "Mailbox 2" },
   { 4, "MBOX3",     0x04C, "Mailbox 3" },
   { 4, "MBOX4",     0x050, "Mailbox 4" },
   { 4, "MBOX5",     0x054, "Mailbox 5" },
   { 4, "MBOX6",     0x058, "Mailbox 6" },
   { 4, "MBOX7",     0x05C, "Mailbox 7" },
   { 4, "P2LDBELL",  0x060, "PCI to local Doorbell" },
   { 4, "L2PDBELL",  0x064, "Local to PCI Doorbell" },
   { 4, "INTCSR",    0x068, "Interrupt Control Status" },
   { 4, "CNTRL",     0x06C, "Serial EEPROM Control, PCI Cmds, User I/O, Init Control" },
   { 4, "PCIHDR",    0x070, "PCI Hardwired Config ID" },
   { 4, "PCIHREV",   0x074, "PCI Hardwired Revision ID" },
   { 4, "MBOX0C",    0x078, "Mailbox 0 Copy" },
   { 4, "MBOX1C",    0x07C, "Mailbox 1 Copy" },
   { 4, "DMAMODE0",  0x080, "DMA Chan 0 Mode" },
   { 4, "DMAPADR0",  0x084, "DMA Chan 0 PCI Address" },
   { 4, "DMALADR0",  0x088, "DMA Chan 0 Local Address" },
   { 4, "DMASIZ0",   0x08C, "DMA Chan 0 Size Bytes" },
   { 4, "DMADPR0",   0x090, "DMA Chan 0 Descriptor Pointer" },
   { 4, "DMAMODE1",  0x094, "DMA Chan 1 Mode" },
   { 4, "DMAPADR1",  0x098, "DMA Chan 1 PCI Address" },
   { 4, "DMALADR1",  0x09C, "DMA Chan 1 Local Address" },
   { 4, "DMASIZ1",   0x0A0, "DMA Chan 1 Size Bytes" },
   { 4, "DMADPR1",   0x0A4, "DMA Chan 1 Descriptor Pointer" },
   { 1, "DMACSR0",   0x0A8, "DMA Chan 0 Command/Status" },
   { 1, "DMACSR1",   0x0A9, "DMA Chan 1 Command/Status" },
   { 2, "AddrAB",    0x0AB, "Reserved" },
   { 4, "DMAARB",    0x0AC, "DMA Arbitration" },
   { 4, "DMATHR",    0x0B0, "DMA Threshold" },
   { 4, "DMADAC0",   0x0B4, "DMA Chan 0 PCI Dual Address Cycle Upper" },
   { 4, "DMADAC1",   0x0B8, "DMA Chan 1 PCI Dual Address Cycle Upper" },
   { 4, "AddrBC",    0x0BC, "Reserved" },
   { 4, "MQCR",      0x0C0, "Message Queue Config" },
   { 4, "QBAR",      0x0C4, "Queue Base Address" },
   { 4, "IFHPR",     0x0C8, "Inbound free head pointer" },
   { 4, "IFTPR",     0x0CC, "Inbound free tail pointer" },
   { 4, "IPHPR",     0x0D0, "Inbound post head pointer" },
   { 4, "IPTPR",     0x0D4, "Inbound post tail pointer" },
   { 4, "OFHPR",     0x0D8, "Outbound free head pointer" },
   { 4, "OFTPR",     0x0DC, "Outbound free tail pointer" },
   { 4, "OPHPR",     0x0E0, "Outbound post head pointer" },
   { 4, "OPTPR",     0x0E4, "Outbound post tail pointer" },
   { 4, "QSR",       0x0E8, "Queue Status/Control" },
   { 4, "AddrEC",    0x0EC, "Reserved" },
   { 4, "LAS1RR",    0x0F0, "Local Address Space 1 Range" },
   { 4, "LAS1BA",    0x0F4, "Local Address Space 1 Local Base Address (Remap)" },
   { 4, "LBRD1",     0x0F8, "Space 1 Bus region" },
   { 4, "DMDAC",     0x0FC, "Direct Master PCI Dual Address Cycles Upper" },
   { 4, "PCIARB",    0x100, "PCI Arbiter Control" },
   { 4, "PABTADR",   0x104, "PCI Abort address" }
 };
