#!/bin/sh
#=======================================================================
# Access to Front-end serial line console
#=======================================================================
set -x

x=`dirname $0`; [ "$x" = "." ] && x=/mcr/bin;
cd $x

# default escape character:
E="-e^[^["


[ $# == 0 ] && {
    ( 	echo "Usage $0 <dsc_name>";
    	echo "      where <dsc_name>  is one of the followings:";
    	echo " - on TN";
    	egrep ^console /acc/sys/adm/conserver.feop  | awk '{print $2}' | sort -u | pr -5 -a -t -w80;
    	echo " - on GPN";
    	egrep ^console /acc/sys/adm/conserver.felab | awk '{print $2}' | sort -u | pr -5 -a -t -w80;
    ) | less
    exit 2
}

U=""
while [ $# -ne 1 ]; do
    case $1 in
	-e*)
	    E="$1"
	    ;;

	*)
	    U="$U $1"
	    ;;
    esac
    shift
done
d="$1"

x=`host $d | egrep -v 'NXDOMAIN|dyndns' | awk '{print $4}'`
[ ! -z "$x" ] && {
    # Host exists  Check for ILO connection request
    case $d in
	cs-*)
	    d1="csm-"${d:3}
	    ;;
	*)
	    d1="$d-ilo"
	    ;;
    esac
    [ `host $d1 | egrep -v 'NXDOMAIN|dyndns' | wc -l` = 1 ] && exec /usr/bin/ssh -l root $U $d1
    M=cs-ccr-feop
    case $x in
	137.138.*)
	    M=cs-ccr-felab
	    ;;
    esac
    exec ./console -M$M $E $U $d
}

# check for this one in straight the lists
x1=`egrep ^console /acc/sys/adm/conserver.feop | awk '{print $2}' | sort -u`
[ `echo $x1 | tr ' ' '\n' | egrep -w ^$d | wc -l` = 1 ] && {
    exec ./console -Mcs-ccr-feop  $E $U $d
}
x2=`egrep ^console /acc/sys/adm/conserver.felab | awk '{print $2}' | sort -u`
[ `echo $x2 | tr ' ' '\n' | egrep -w ^$d | wc -l` = 1 ] && {
    exec ./console -Mcs-ccr-felab $E $U $d
}


# If non-ambiguous name connect
[ `echo $x1 | tr ' ' '\n' | egrep $d | wc -l` = 1 ] && {
    d=`echo $x1 | tr ' ' '\n' | egrep $d`;
    exec ./console -Mcs-ccr-feop  $E $U $d
}
[ `echo $x2 | tr ' ' '\n' | egrep $d | wc -l` = 1 ] && {
    d=`echo $x2 | tr ' ' '\n' | egrep $d`;
    exec ./console -Mcs-ccr-felab $E $U $d
}
y=`echo $x1 $x2 | tr ' ' '\n' | egrep $d`
[ $? -ne 0 ] && {
    echo There is no console for $d - sorry
    echo "===================================================================="
    exit 2
}
echo "===================================================================="
echo $d is ambiguous: Please choose one of the followings:
echo $x1 $x2 | tr ' ' '\n' | egrep $d | pr -5 -a -t -w80
echo "===================================================================="
exit 2

