#!/bin/bash
# HOWTO compile the driver with local CDCM copy.

# Goto local CDCM. Edit. Compile.
cd  coht/.__kitchen/ygeorgie/cdcm; ./rmdrv; make

# Goto your driver dir
cd <your_driver>; ./rmdrvr;

make CPU=L865 CDCM_D=/acc/src/dsc/drivers/coht/.__kitchen/ygeorgie
