###############################################################################
# @file Kbuild
#
# @brief Specific kbuild
#
# @author Yury GEORGIEVSKIY, CERN.
#
# @date Created on 14/01/2009
#
# @version
###############################################################################

# Use ccflags-y to pass extra driver compilation flags (if any)
# ccflags-y =

#  Use XTRA_DRSC to add driver files to compile from other
#+ then ./driver directories
#+ Path should be relative to the cwd!
# XTRA_DSRC =

# include general kbuild
include $(M)/../../makefiles/Kbuild
