EXTRA_CFLAGS=-I $(src)/../../include
obj-m += modulbus_register.o 
obj-m += mod-pci.o vmodio.o 
obj-m += vmodttl.o vmoddor.o vmod12a2.o
obj-m += vmod12e16.o vmod16a2.o
obj-m += vmodttl.o 

vmoddor-objs := lunargs.o vmoddordrvr.o
vmod12a2-objs := lunargs.o vmod12a2drvr.o
vmod12e16-objs := lunargs.o vmod12e16drvr.o
vmod16a2-objs := lunargs.o vmod16a2drvr.o
vmodttl-objs := lunargs.o vmodttldrvr.o
