###############################################################################
# @file Kbuild
#
# @brief TEMPLATE. Specific kbuild for compiling Linux driver
#
# @author Yury GEORGIEVSKIY, CERN.
#
# Should be adapted for a specific driver
#
# @date Created on 29/04/2009
###############################################################################

# Use ccflags-y to pass extra driver compilation flags (if any)
# To compile for 2.6.9 -- EXTRA_CFLAGS should be used instead.
# ccflags-y =
# EXTRA_CFLAGS =

#  Use XTRA_DRSC to add driver files to compile from other
#+ then ./driver directories
#+ Path should be relative to the cwd!
# XTRA_DSRC =

# Space separated list of driver directories this driver depends on
DEP_SYMVERS = /acc/src/dsc/drivers/coht/vmebridge

# include standart general kbuild
include $(ROOTDIR)/makefiles/Kbuild
