###############################################################################
# @file Makefile
#
# @brief Makefile to compile module benchmark.
#
# It includes driver, libraries and test programs.
#
# @author Yury GEORGIEVSKIY, CERN.
#
# @date Created on 13/01/2009
###############################################################################

-include Makefile.specific

# Standard driver directory tree layout
SUBDIRS += \
	lib \
	include \
	test \
	driver

include $(ROOTDIR)/makefiles/Makefile.base
