###############################################################################
# @file Makeflie.lib
#
# @brief Library compilation.
#
# @author Yury GEORGIEVSKIY, CERN.
#
# @date Created on 13/01/2009
###############################################################################

# Makefile from current directory supress one from upper level
include $(shell if [ -e ./Makefile.specific ]; then \
		echo ./Makefile.specific; \
	else \
		echo ../Makefile.specific; \
	fi)

include ../Makefile

ADDCFLAGS += $(STDFLAGS) -DDRIVER_NAME=\"$(DRIVER_NAME)\"

INCDIRS = \
	../include \
	../../include

SRCFILES = \
	$(wildcard *.c)

LIBRARIES = lib$(DRIVER_NAME).$(CPU).a

$(LIBRARIES): $(OBJFILES)
	$(Q)$(AR) -rv $@ $(XTRA_USR_LIBS) $^
	$(Q)$(RANLIB) $@
	$(Q)$(RM) $(OBJFILES)

_build: $(LIBRARIES)
	$(Q)mv $(LIBRARIES) ../$(FINAL_DEST)

linux:
	@echo -e "\nCompiling for Linux:"
	$(Q)$(MAKE) _build CPU=L865

lynx:
	@echo -e "\nCompiling for Lynx:"
	$(Q)$(MAKE) _build CPU=ppc4

all:
	$(Q)$(MAKE) linux
	$(Q)$(MAKE) lynx

