###############################################################################
# @file Makeflie.lib
#
# @brief Library compilation.
#
# @author Yury GEORGIEVSKIY, CERN.
#
# @date Created on 13/01/2009
###############################################################################

# Makefile from current directory supress one from upper level
include $(shell if [ -e ./Makefile.specific ]; then \
		echo ./Makefile.specific; \
	else \
		echo ../Makefile.specific; \
	fi)

include ../Makefile

ADDCFLAGS += $(STDFLAGS) -DDRIVER_NAME=\"$(DRIVER_NAME)\"

INCDIRS = \
	../include \
	../../include

SRCFILES = \
	$(wildcard *.c)

############################################################################
#      Rules to build .a library.                                          #
############################################################################
lib$(DRIVER_NAME)$(EXTLIB): lib$(DRIVER_NAME)$(EXTLIB)($(OBJFILES))
	$(Q)$(RANLIB) $@
	$(Q)mv $@ ../$(FINAL_DEST)/$(@:%.a=%.$(CPU).a)

LIBRARIES += lib$(DRIVER_NAME)$(EXTLIB)
############################################################################

############################################################################
#      If we need to build a .so libraries.                                #
############################################################################
ifeq ($(COMPILE_LIB_SHARED),y)
ADDCFLAGS += -fPIC

# Create .so object
lib$(DRIVER_NAME)$(EXTSO): $(OBJFILES)
	$(Q)$(CC) -shared -Wl,-export-dynamic -Wl,-soname,$(@:%.so=%.$(CPU).so) -o $@ $(OBJFILES)
	$(Q)mv $@ ../$(FINAL_DEST)/$(@:%.so=%.$(CPU).so)

LIBRARIES += lib$(DRIVER_NAME)$(EXTSO)
endif
############################################################################

_build: $(FINAL_DEST) $(LIBRARIES)
	$(Q)$(RM) $(OBJFILES)

all:
	$(Q)$(MAKE) _build CPU=$(CPU)

# CERN delivery
include ../$(ROOTDIR)/makefiles/deliver.mk
