#!/bin/bash
################################################################################
# @file rmdrvr
#
# @brief Cleaning up drivers.
#
# @author Yury GEORGIEVSKIY, CERN.
#
# @date Created on 08/04/2009
################################################################################
rm -f *.o .*.o.cmd .*.o.d .*.ko.cmd *.ko *.mod.c
rm -fr .tmp_versions/ LYNX603_4.0.0_* LINUX_CES_*
rm -f /tmp/shlvcompvars
rm -fr *.o .*.o.cmd .*.o.d .*.o.tmp .tmp_*.o .tmp_versions/ Module.symvers *.o_shipped \
    Module.markers modules.order
